version: "3.7"

services:
  db:
    image: mariadb:10.4.6-bionic
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: oop3iaBa
    volumes:
      - mariadb-data-dir:/var/lib/mysql

  redis:
    image: redis:5.0.5
    volumes:
      - redis-data-dir:/data

  web:
    build:
      context: .
      target: base
    command: /app/bin/run-apache
    working_dir: /app
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
      - ./vendor/phpipam:/var/www/phpipam
      - ./conf/config.php:/var/www/phpipam/config.php
      - ./conf/000-phpipam.conf:/etc/apache2/sites-enabled/000-phpipam.conf
      - ./conf/99-php-error-log.ini:/etc/php/7.3/apache2/conf.d/99-error-log.ini
      - ./conf/99-php-redis-sessions.ini:/etc/php/7.3/apache2/conf.d/99-redis-session.ini
    environment:
      MYSQL_ROOT_PASSWORD: oop3iaBa

      DB_HOST: db
      DB_USER: phpipam
      DB_PASSWORD: phpipamadmin
      DB_NAME: phpipam

      GMAPS_API_KEY: ${GMAPS_API_KEY}
    entrypoint: /app/bin/entrypoint
    ports:
      - "8080:80"

volumes:
  mariadb-data-dir: ~
  redis-data-dir: ~
